dist: xenial
sudo: required
addons:
    snaps:
        -hugo

script:
    - hugo -D

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $PAGES_GITHUB_TOKEN
    local_dir: ./public
    fqdn: www.piqueserver.org
